#!/opt/freeware/bin/bash

# Check dependencies
echo "Checking dependencies..."
expat_version=$(rpm -qa|grep expat 2>&1)
flag=0
if [[ "${expat_version}" != "expat-2.1.0-1.ppc" ]]; then
  echo "Expat version is not equal to dependented 2.1.0-1 version."
  flag=1
else
  echo "expat ok"
fi
gettext_version=$(rpm -qa|grep gettext 2>&1)
if [[ "${gettext_version}" != "gettext-0.17-8.ppc" ]]; then
  echo "${gettext_version} is not equal to dependented 0.17-8 version."
  flag=1
else
  echo "gettext ok"
fi
glib_version=$(rpm -qa|grep glib 2>&1)
if [[ "${glib_version}" != "glib2-2.14.6-2.ppc" ]]; then
  echo "${glib_version} is not equal to dependented 2.14.6-2 version."
  flag=1
else
  echo "glib ok"
fi
libicon_version=$(rpm -qa|grep libicon 2>&1)
if [[ "${libicon_version}" != "libiconv-1.14-1.ppc" ]]; then
  echo "${libicon_version} is not equal to dependented 1.14-1 version."
  flag=1
else
  echo "libicon ok"
fi

# If missmatch is found between required dependencies, ask user if thats ok
if [ $flag -eq 1 ]; then
  echo "There was exception with dependencies."
  echo "Please update older versions. Newer versions might work."
  read -p "Continue y/n?" -n 1 -r
  echo
  if [[ "$REPLY" =~ ^[nN]$ ]]; then
    echo "Exiting."
    exit 1
  fi
fi

if [ $(grep zabbix /etc/group | wc -l) -gt 0 ]; then
  echo "Zabbix group already exists"
else
  echo "Creating user group for Zabbix"
  mkgroup zabbix
fi

if [ $(grep zabbix /etc/passwd | wc -l) -gt 0 ]; then
  echo "Zabbix user already exists"
else
  echo "Creating user for Zabbix agent"
  mkuser pgrp='zabbix' groups='zabbix' zabbix
fi

# Check that script.gz.tar exists
if [ ! -e scripts ]; then
  echo "Script package missing from installation folder."
  exit 1
fi

echo "Creating installation folder for Zabbix agent under /opt/freeware/, if already not exist"
mkdir -p /opt/freeware/zabbix
chgrp -R zabbix /opt/freeware/zabbix/

if [ -e /opt/freeware/zabbix/sbin/zabbix_agentd ]; then
  echo "Zabbix agent already installed, please remove it first."
  exit 1
elif [ ! -e zabbix-agent-3.0.7-1.aix6.1.ppc.rpm ]; then
  echo "Zabbix-agent rpm-package not found"
  exit 1
else
  echo "Installing rpm-package"
  rpm -Uhvh --prefix=/opt/freeware/zabbix/ zabbix-agent-3.0.7-1.aix6.1.ppc.rpm
fi

# Default configuration changes
# Do not specify Hostname but use system hostname by default
sed -i '/^Hostname=Zabbix server/d' opt/freeware/zabbix/etc/zabbix_agentd.conf
# Bigger timeout
sed -i '/^# Timeout=3/a Timeout=15' opt/freeware/zabbix/etc/zabbix_agentd.conf

echo "Making logging folder for zabbix and changing it's permissions under /var/log/"
mkdir -p /var/log/zabbix
chown -R zabbix:system /var/log/zabbix
chmod -R o+r /var/log/zabbix

echo "Making pid-file folder for zabbix and changing it's permissions under /var/run/"
mkdir -p /var/run/zabbix/
chown -R zabbix:system /var/run/zabbix
chmod -R o+r /var/run/zabbix

echo "Moving start and stop scripts under /etc/rc.d/init.d/ and linking it to run level directory"
if [ -e zabbix-agent ]; then
  cp zabbix-agent /etc/rc.d/init.d/
  ln -s -f /etc/rc.d/init.d/zabbix-agent /etc/rc.d/rc2.d/Szabbix-agent
  ln -s -f /etc/rc.d/init.d/zabbix-agent /etc/rc.d/rc2.d/Kzabbix-agent
else
  echo "Cant find zabbix-agent script. Make sure it is in the same folder with this installation script"
  exit 1
fi

echo "Installation done."
